kind: pipeline
type: docker
name: db-metadata演示环境CI/CD

# 集中式的大仓库使用如下方式进行代码提交
# ${DRONE_COMMIT_MESSAGE%%;*} 获取版本号
# ${DRONE_COMMIT_MESSAGE##*;} 项目名称
# 代码提交的message格式为{}内的内容,不包含{}：{1.0.0;更新了一个服务;approval-web} 版本号;更新了内容;项目名称

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./.m2
        - ./web/node_modules
    when:
      local: false

  - name: build-web
    image: node:12.16
    commands:
      - cd web
      - npm cache clean --force
      - npm install
      - npm run build:prod
    when:
      local: false

  - name: build-server
    image: maven:3-alpine
    commands:
      - ls /root/.m2/repository
      - mvn clean -U package -DskipTests
    volumes:
      - name: maven-repo
        path: /root/.m2/repository
    when:
      local: false

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./.m2
        - ./web/node_modules
    when:
      local: false

  - name: push
    image: plugins/docker
    privileged: true
    settings:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - sh build.sh ${DRONE_BUILD_NUMBER} $${DRONE_COMMIT_MESSAGE##*;}
    when:
      local: false

  - name: deploy-ui
    image: hthj-registry.cn-hangzhou.cr.aliyuncs.com/hthj_base/drone-k8s-update
    settings:
      kubernetes_server: https://rancher.asoco.com.cn/k8s/clusters/local
      kubernetes_token:
        from_secret: k8s_token
      namespace: system-tool
      deployment: db-metadata-web
      repo: hthj-registry.cn-hangzhou.cr.aliyuncs.com/hthj_asoco/db-metadata-demo-web
      container: db-metadata-web
      tag: ${DRONE_BUILD_NUMBER}
    when:
      event:
        - push
      local: false

  - name: deploy-server
    image: hthj-registry.cn-hangzhou.cr.aliyuncs.com/hthj_base/drone-k8s-update
    settings:
      kubernetes_server: https://rancher.asoco.com.cn/k8s/clusters/local
      kubernetes_token:
        from_secret: k8s_token
      namespace: system-tool
      deployment: db-metadata-server
      repo: hthj-registry.cn-hangzhou.cr.aliyuncs.com/hthj_asoco/db-metadata-demo-server
      container: db-metadata-server
      tag: ${DRONE_BUILD_NUMBER}
    when:
      event:
        - push
      local: false

trigger:
  ref:
    - refs/heads/master

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: docker
    host:
      path: /var/run/docker.sock
  - name: maven-repo
    host:
      path: /tem/maven-repo
