server:
  port: 8888

logging:
  level:
    self: debug
    root: info
  group:
    self: com.hthjsj.md.demo,com.github.md

spring:
  datasource:
    url: jdbc:mysql://${your_db_ip}:${your_db_port}/${your_db_name}?useSSL=false&characterEncoding=utf-8
    username: ${your_db_username}
    password: ${your_db_password}
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

# db-metadata完整的默认配置
md:
  dev-mode: true # 开发模式。为true时系统将允许一些操作(比如清空元对象，重新全量生成等)
  version: 2.4 # dbmeta版本号
  app: # 应用配置
    name: DB-Metadata低代码开发框架-演示 # 系统名
    logo: meta # 系统logo地址
    registerable: false # 系统是否支持用户自行注册
    addable: true # 系统是否支持用户添加其他用户
    default_pass: 888888 # 默认(初始)密码， 当添加用户时、用户注册(未提供密码时)，将使用此默认密码
    pass-encrypt-key: DB-Metadata is delicious # 用户密码加密密钥。无论什么方式，入库的明文密码都需要使用此密钥进行加密。加密方式为AES对称加密。此密钥一旦设定，如果更改，可能导致用户服务登录，只能重置了。
    login-bg: \#2f4a75 # 登录页背景色(如blue、#0000FF)或背景图(地址，会设置到url()中)
    reset-pass: dbmeta # 重置口令, 默认dbmeta
    show-version: true # 在系统名前显示dbmeta版本号
    show-greeting: true # 显示问候语
    show-theme-setting: true # 显示主题设置入口, 设为false，则用户无法设置主题
    allow-custom-theme: false # 是否允许用户自由配置主题。用户界面上设置的主题只影响其本地。
    doc-url: http://dbmeta.pengxg.cc # db-meta文档地址

  server:
    enable-certification: true # 是否启用认证，若关闭, 则不用登录，不用鉴权。
    login: # 认证配置
      cookie-key: DB-Metadata # 登录后自动存放到cookie中的token的key
      token-key: ASOCO-TOKEN # 登录后存放在header里的token的 key
      login-key: username # 登录表单账号的key
      pwd-key: password # 登录表单密码的key
      includes: # 需要认证的接口
        - /**
      excludes: # 无需认证的接口url
        - /app/config
        - /router
        - /user/login
      ctrl:
        enable: true # 是否启用内置登录控制器(接口)，若关闭则以下接口无效。需要自行提供登录接口
        login-path: /user/login # 内置登录接口
        logout-path: /user/logout # 内置登出接口
        info-path: /user/info # 内置用户信息接口
    auth: # 鉴权配置
      includes: # 需要鉴权的接口
        - /**
      excludes: # 无需鉴权的接口url
        - /app/config
        - /router
        - /user/login
    upload: # 上传配置
      mode: local # 上传采用的模式。默认为local, 表示上传到服务器本地目录(具体路径取决于md.server.upload.local下的配置)。
      local:
        base-upload-path: /opt/www/db-meta-serve # 当mode为本地时，配置的本地上传根路径

    event-enabled: true
    component:
      replace-from-json-file: false # 是否开启每次启动时从json文件(defaultInstance.json)中推导组件实例配置，并覆盖数据库
    meta-object:
      replace-from-json-file: false # 是否开启每次启动时从json文件(defaultObject.json)中推导元对象逻辑配置，并覆盖数据库
    instance:
      recompute-when-meta-field-update: false # 元字段更新时，是否重新计算元字段的UI实例配置。默认是false

  analysis:
    show-sql: true
    extension:
      meta-object-enabled: true
      meta-field-enabled: true
      component-instance-enabled: true
