name: ci/cd to personal server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Source build【server】
        run: |
          echo 'start to build db-metadata-demo'
          mvn -DskipTests=true clean install

#      - name: Docker build and push to docker hub 【server】
#        uses: mr-smithers-excellent/docker-build-push@v6
#        with:
#          image: pengxg/db-metadata-demo-server
##          tags: ${{github.run_number}}
#          tags: latest
#          registry: docker.io
#          dockerfile: ./server/Dockerfile
#          directory: ./server
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Source build【web】
        uses: actions/setup-node@v3
        with:
          node-version: 12.22.12
      - run: cd ./web && npm install && npm run build:prod

#      - name: Docker build and push to docker hub 【web】
#        uses: mr-smithers-excellent/docker-build-push@v6
#        with:
#          image: pengxg/db-metadata-demo-web
##          tags: ${{github.run_number}}
#          tags: latest
#          registry: docker.io
#          dockerfile: ./web/Dockerfile
#          directory: ./web
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker version
          docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          docker build ./server -f ./server/Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/dbmeta/db-metadata-demo-server:latest
          docker push registry.cn-hangzhou.aliyuncs.com/dbmeta/db-metadata-demo-server:latest
          docker build ./web -f ./web/Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/dbmeta/db-metadata-demo-web:latest
          docker push registry.cn-hangzhou.aliyuncs.com/dbmeta/db-metadata-demo-web:latest

      - name: Ssh deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} registry.cn-hangzhou.aliyuncs.com && cd /root/.dbmeta && sh update.sh


