name: ci/cd to personal server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Source build
        run: |
          echo 'local install db-metadata'
          git clone https://github.com/pengxianggui/db-metadata.git
          cd db-metadata/db-metadata-parent
          mvn -DskipTests=true clean package
          echo 'start to build db-metadata-demo'
          cd ../../server
          mvn -DskipTests=true clean install
          cd ../web
          npm install && npm build:prod

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker build and push docker image 【server】
        uses: docker/build-push-action@v4
        with:
          push: true
          content: ./server

      - name: Docker build and push docker image 【web】
        uses: docker/build-push-action@v4
        with:
          push: true
          content: ./web

      - name: Ssh deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: cd /root/db-metadata/db-metadata-demo && sh deploy.sh ${{ secrets.DOCKERHUB_USERNAME }} ${{secrets.DOCKERHUB_PASSWORD}}


